import React from "react";

const AdminPage = () => {
    return (
        <>
        <h1>Welcome to the admin page</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur lectus id augue gravida, in volutpat ligula posuere. Sed congue, urna sed aliquet eleifend, turpis odio vehicula libero, nec dapibus orci arcu a lectus. Morbi auctor tortor non ipsum blandit, sed aliquam est ultrices. Fusce gravida est ac malesuada iaculis. Aliquam dignissim auctor libero, ut dapibus ligula bibendum eu. Nam pharetra justo vel finibus suscipit. Praesent rutrum ligula at tortor rhoncus viverra. Suspendisse egestas finibus feugiat. Vivamus ultrices ante sit amet justo dignissim ultrices. Mauris et arcu felis. Integer ut condimentum leo, nec blandit ex. Donec consequat varius quam, sit amet eleifend mi tempus eget.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur lectus id augue gravida, in volutpat ligula posuere. Sed congue, urna sed aliquet eleifend, turpis odio vehicula libero, nec dapibus orci arcu a lectus. Morbi auctor tortor non ipsum blandit, sed aliquam est ultrices. Fusce gravida est ac malesuada iaculis. Aliquam dignissim auctor libero, ut dapibus ligula bibendum eu. Nam pharetra justo vel finibus suscipit. Praesent rutrum ligula at tortor rhoncus viverra. Suspendisse egestas finibus feugiat. Vivamus ultrices ante sit amet justo dignissim ultrices. Mauris et arcu felis. Integer ut condimentum leo, nec blandit ex. Donec consequat varius quam, sit amet eleifend mi tempus eget.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur lectus id augue gravida, in volutpat ligula posuere. Sed congue, urna sed aliquet eleifend, turpis odio vehicula libero, nec dapibus orci arcu a lectus. Morbi auctor tortor non ipsum blandit, sed aliquam est ultrices. Fusce gravida est ac malesuada iaculis. Aliquam dignissim auctor libero, ut dapibus ligula bibendum eu. Nam pharetra justo vel finibus suscipit. Praesent rutrum ligula at tortor rhoncus viverra. Suspendisse egestas finibus feugiat. Vivamus ultrices ante sit amet justo dignissim ultrices. Mauris et arcu felis. Integer ut condimentum leo, nec blandit ex. Donec consequat varius quam, sit amet eleifend mi tempus eget.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec efficitur lectus id augue gravida, in volutpat ligula posuere. Sed congue, urna sed aliquet eleifend, turpis odio vehicula libero, nec dapibus orci arcu a lectus. Morbi auctor tortor non ipsum blandit, sed aliquam est ultrices. Fusce gravida est ac malesuada iaculis. Aliquam dignissim auctor libero, ut dapibus ligula bibendum eu. Nam pharetra justo vel finibus suscipit. Praesent rutrum ligula at tortor rhoncus viverra. Suspendisse egestas finibus feugiat. Vivamus ultrices ante sit amet justo dignissim ultrices. Mauris et arcu felis. Integer ut condimentum leo, nec blandit ex. Donec consequat varius quam, sit amet eleifend mi tempus eget.</p>
        </> 
    )
    
}

export default AdminPage;